### ISSUE TITLE
Some questions about data resize

### ISSUE THREAD

**Issue by ypbhc1998** [SLKaMiHi/TD-Net-unsupervised-medical-image-registration-network-based-on-Transformer-and-CNN#1]
您好，我通过阅读文章发现在文章中您将Oasis数据集resize到[96×112×96]但是初始dice为0.5651，我使用的Oasis数据集大小为[140,166,140]初始dice在0.56附近，但是当我将它resize到96×112×96时，它的初始DICE只有0.3371。在我实验的过程中，我发现只要resize图片缩小尺寸，初始DICE就会降低，我不知道这是不是一个正常现象？还是我数据处理resize的时候出现了问题？如果可以的话，您可以将数据resize的代码公开一下吗？非常感谢。

**Comment by SLKaMiHi** [comment]
我是使用了scipy.ndimage.zoom() 函数进行的缩放操作。并且对于图像使用了双线性插值，对于label使用了最邻近插值。我的图像是从（160，192，224）的尺寸缩放到（96，112，96），我觉得可能是这个的影响。另外我不知道我们缩放的维度是否对应。希望能对你有所帮助。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SLKaMiHi/TD-Net-unsupervised-medical-image-registration-network-based-on-Transformer-and-CNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 中午11:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[SLKaMiHi/TD-Net-unsupervised-medical-image-registration-network-based-on-Transformer-and-CNN] Some questions about data resize (Issue #1)





 
您好，我通过阅读文章发现在文章中您将Oasis数据集resize到[96×112×96]但是初始dice为0.5651，我使用的Oasis数据集大小为[140,166,140]初始dice在0.56附近，但是当我将它resize到96×112×96时，它的初始DICE只有0.3371。在我实验的过程中，我发现只要resize图片缩小尺寸，初始DICE就会降低，我不知道这是不是一个正常现象？还是我数据处理resize的时候出现了问题？如果可以的话，您可以将数据resize的代码公开一下吗？非常感谢。

**Comment by ypbhc1998** [comment]
> 我是使用了scipy.ndimage.zoom() 函数进行的缩放操作。并且对于图像使用了双线性插值，对于label使用了最邻近插值。我的图像是从（160，192，224）的尺寸缩放到（96，112，96），我觉得可能是这个的影响。另外我不知道我们缩放的维度是否对应。希望能对你有所帮助。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SLKaMiHi/TD-Net-unsupervised-medical-image-registration-network-based-on-Transformer-and-CNN" ***@***.***&gt;; 发送时间:&nbsp;2022年4月19日(星期二) 中午11:12 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[SLKaMiHi/TD-Net-unsupervised-medical-image-registration-network-based-on-Transformer-and-CNN] Some questions about data resize (Issue #1) 您好，我通过阅读文章发现在文章中您将Oasis数据集resize到[96×112×96]但是初始dice为0.5651，我使用的Oasis数据集大小为[140,166,140]初始dice在0.56附近，但是当我将它resize到96×112×96时，它的初始DICE只有0.3371。在我实验的过程中，我发现只要resize图片缩小尺寸，初始DICE就会降低，我不知道这是不是一个正常现象？还是我数据处理resize的时候出现了问题？如果可以的话，您可以将数据resize的代码公开一下吗？非常感谢。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

**Comment by ypbhc1998** [comment]
非常感谢你！我换了这个函数之后测试了一下发现我缩放后的图像dice没有降低了，这真的对我帮助很大~再次感谢!!
