### ISSUE TITLE
Some questions about dataset

### ISSUE THREAD

**Issue by B1GGUN** [SLKaMiHi/TD-Net-unsupervised-medical-image-registration-network-based-on-Transformer-and-CNN#2]
您好，虽然很冒昧，但请问能分享一下您处理过的数据集嘛。OASIS我注册下载后，自己进行预处理，但是每每test的dice都很低，用Vm跑的甚至不到0.5，然而我反复看了又看改了又改，数据集的问题始终没有解决，如果能分享一下您的数据集，我将不胜感激，谢谢！

**Comment by SLKaMiHi** [comment]
你可以在这里找到数据集
https://github.com/adalca/medical-datasets/blob/master/neurite-oasis.md




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SLKaMiHi/TD-Net-unsupervised-medical-image-registration-network-based-on-Transformer-and-CNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月9日(星期一) 晚上10:25
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[SLKaMiHi/TD-Net-unsupervised-medical-image-registration-network-based-on-Transformer-and-CNN] Some questions about dataset (Issue #2)





 
您好，虽然很冒昧，但请问能分享一下您处理过的数据集嘛。OASIS我注册下载后，自己进行预处理，但是每每test的dice都很低，用Vm跑的甚至不到0.5，然而我反复看了又看改了又改，数据集的问题始终没有解决，如果能分享一下您的数据集，我将不胜感激，谢谢！
